namespace image_channel_viewer
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        String LocalizedString(String resourceId);
    }
}